schema_version = "1.0.1"

id = "watershapegenerator"
version = "1.0.1"
name = "水体生成器"
tagline = "强大的水体和流体生成工具，支持多种预设和实时参数调节"
maintainer = "Xi Lin <your-email@example.com>"
type = "add-on"

# 项目链接
website = "https://github.com/LifeSugar/WaterShapeGenerator"

# 支持的标签
tags = ["3D View", "Modeling", "Geometry Nodes", "Animation", "Simulation"]

blender_version_min = "4.2.0"

# 开源许可证
license = [
  "SPDX:GPL-3.0-or-later",
]

# 版权信息
copyright = [
  "2025 Xi Lin",
]

# 支持的平台
platforms = ["windows-x64", "macos-arm64", "linux-x64", "macos-x64", "windows-arm64"]

# 权限说明
[permissions]
files = "需要读取水体预设文件和图标资源"

# 构建设置
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/debug_*.txt",
  "/.vscode/",
  "/node_modules/",
]